{
 "title": "test",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pvname", "query": "zheng1:ai3" }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pvs" },
  {
   "title": "pv总数量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "formatType": "Time series", "sql": "show pvs.tables;" }
   ]
  },
  {
   "title": "在线pv数量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select sum(a) from (select last(val) as a from status.st group by tbname) ;"
    }
   ]
  },
  {
   "title": "回调次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select * from monitor.monitor_pv;"
    }
   ]
  },
  { "title": "搜索结果", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "formatType": "Time series", "sql": "select * from pvs.`$pvname`;" }
   ]
  },
  {
   "title": "status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select * from status.`$pvname`;"
    }
   ]
  },
  { "title": "caMonitor状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "caMonitor状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "formatType": "Time series", "sql": "select * from monitor.monitor;" }
   ]
  }
 ]
}